//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestToUser
    {
        public int Id { get; set; }
        public Nullable<int> IdTest { get; set; }
        public string IdAspNetUsers { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Test Test { get; set; }
    }
}
