//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Otcestvo { get; set; }
        public int Dolgnost { get; set; }
        public string Kurs { get; set; }
        public string Passvord { get; set; }
        public string Login { get; set; }
    
        public virtual Dolgnost Dolgnost1 { get; set; }
    }
}
