//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestAspEntities : DbContext
    {
        public TestAspEntities()
            : base("name=TestAspEntities")
        {
        }

        private static TestAspEntities db;
        public static TestAspEntities GetEntities()
        {
            if (db == null)
                db = new TestAspEntities();
            return db;

        }
        public static TestAspEntities Get()
        {
            db = new TestAspEntities();
            return db;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dolgnost> Dolgnost { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestToUser> TestToUser { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
